micronaut:
  application:
    name: dynamicBeanCreation
netty:
  default:
    allocator:
      max-order: 3
---
participants:
  First Participant:
    username: first
    publishers:
      First Publisher:
        writers-class-names:
          - "com.example.FirstSubclass"
          - "com.example.SecondSubclass"
          - "com.example.SecondSubclass"
      Second Publisher:
        writers-class-names:
          - "com.example.SecondSubclass"
